package: knowledgebase
version: '0.9.6'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO

requires:
    redaxo: ^5.18
    php: ^8.2
    yform: ^5.0
    packages:
        fields: '>=1.4.0'
        yform_content_builder: '*'

page:
    title: 'Knowledge Base'
    perm: knowledgebase[]
    icon: rex-icon fa-book
    block: system
    subpages:
        overview:
            title: 'Übersicht'
            perm: knowledgebase[overview]
        articles:
            title: 'Beiträge'
            subPath: pages/articles.php
            perm: knowledgebase[articles]
        bases:
            title: 'Wissensbasen'
            subPath: pages/yform.php
            perm: knowledgebase[bases]
        glossary:
            title: 'Glossar'
            subPath: pages/yform.php
            perm: knowledgebase[glossary]
        interactive_images:
            title: 'Interaktive Bilder'
            subPath: pages/yform.php
            perm: knowledgebase[interactive_images]
        settings:
            title: 'Einstellungen'
            subPath: pages/settings.php
            perm: admin
        frontend_texts:
            title: 'Frontend-Texte'
            subPath: pages/frontend_texts.php
            perm: knowledgebase[frontend_texts]

autoload:
    classes:
        FriendsOfREDAXO\Knowledgebase\: lib/

yform:
    knowledgebase/bases:
        table_name: knowledgebase
    knowledgebase/articles:
        table_name: knowledgebase_article
    knowledgebase/glossary:
        table_name: knowledgebase_glossary
    knowledgebase/interactive_images:
        table_name: knowledgebase_interactive_image